import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Download, FileText, CheckCheck } from "lucide-react";
import { PageHeader } from "@/components/dashboard/DashLayout";
import { WorkflowBanner, AIEyebrow, TrackedChange } from "@/components/ai";
import { CEEVEE_CV_EDITS, CEEVEE_CANDIDATE } from "@/lib/mock-data";

export const Route = createFileRoute("/jobseeker/ceevee/review")({
  component: CeeVeeReview,
});

function CeeVeeReview() {
  const [edits, setEdits] = useState(CEEVEE_CV_EDITS.map((e) => ({ ...e })));

  const setAccepted = (index: number, accepted: boolean) =>
    setEdits((prev) => prev.map((e, i) => (i === index ? { ...e, accepted } : e)));

  const acceptAll = () => setEdits((prev) => prev.map((e) => ({ ...e, accepted: true })));

  const acceptedCount = edits.filter((e) => e.accepted).length;
  const pendingCount = edits.length - acceptedCount;

  // Group edits by section, preserving order and original index for state wiring.
  const sections: { section: string; items: { edit: (typeof edits)[number]; index: number }[] }[] = [];
  edits.forEach((edit, index) => {
    const existing = sections.find((s) => s.section === edit.section);
    if (existing) existing.items.push({ edit, index });
    else sections.push({ section: edit.section, items: [{ edit, index }] });
  });

  return (
    <div>
      <WorkflowBanner
        workflow="AI Assistant"
        step="CV Review"
        next={{ label: "What AI knows", to: "/jobseeker/ceevee/status" }}
      />

      <PageHeader
        title={`CV Review - ${CEEVEE_CANDIDATE.name}`}
        subtitle="AI-tracked CV suggestions, review line by line"
        actions={
          <button
            type="button"
            className="inline-flex items-center gap-2 rounded-full bg-accent-lime px-5 py-2.5 text-sm text-accent-lime-foreground tracking-tight"
          >
            <Download className="h-4 w-4" />
            Export PDF
          </button>
        }
      />

      {/* Summary strip */}
      <div className="mt-2 flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-surface border border-border p-5">
        <div className="flex flex-wrap items-center gap-6">
          <div>
            <div className="text-[11px] uppercase tracking-wider text-muted-ink">Accepted</div>
            <div className="mt-1 text-2xl text-ink tracking-tight">{acceptedCount}</div>
          </div>
          <div className="h-10 w-px bg-border" aria-hidden="true" />
          <div>
            <div className="text-[11px] uppercase tracking-wider text-muted-ink">Pending</div>
            <div className="mt-1 text-2xl text-ink tracking-tight">{pendingCount}</div>
          </div>
          <div className="hidden sm:block max-w-xs text-xs text-muted-ink leading-relaxed">
            Accepted edits are applied to your exported CV. Pending ones keep your original wording.
          </div>
        </div>
        <button
          type="button"
          onClick={acceptAll}
          disabled={pendingCount === 0}
          className="inline-flex items-center gap-2 rounded-full bg-surface-alt px-4 py-2.5 text-sm text-ink tracking-tight disabled:opacity-40"
        >
          <CheckCheck className="h-4 w-4" />
          Accept all
        </button>
      </div>

      {/* Paper-like document */}
      <div className="mt-6 mx-auto max-w-3xl rounded-2xl bg-surface border border-border p-6 md:p-8 shadow-[0_10px_40px_-15px_rgba(0,0,0,0.25)]">
        <div className="flex items-start gap-3 border-b border-border pb-5">
          <span className="grid h-10 w-10 place-items-center rounded-full bg-brand/10 text-brand shrink-0">
            <FileText className="h-5 w-5" />
          </span>
          <div>
            <h2 className="text-lg text-ink tracking-tight">{CEEVEE_CANDIDATE.name}</h2>
            <p className="text-sm text-muted-ink">
              {CEEVEE_CANDIDATE.targetRole} · {CEEVEE_CANDIDATE.location} · {CEEVEE_CANDIDATE.experience}
            </p>
          </div>
        </div>

        <div className="pt-5">
          <AIEyebrow>Generated by AI from your profile + market data</AIEyebrow>
        </div>

        <div className="mt-6 space-y-8">
          {sections.map((group) => (
            <section key={group.section}>
              <div className="mb-3 flex items-center gap-3">
                <h3 className="text-sm uppercase tracking-wider text-brand">{group.section}</h3>
                <div className="h-px flex-1 bg-border" aria-hidden="true" />
              </div>
              <div className="space-y-4">
                {group.items.map(({ edit, index }) => (
                  <TrackedChange
                    key={index}
                    section={group.section}
                    original={edit.original}
                    improved={edit.improved}
                    rationale={edit.rationale}
                    accepted={edit.accepted}
                    onAccept={() => setAccepted(index, true)}
                    onReject={() => setAccepted(index, false)}
                  />
                ))}
              </div>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
