/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobseekerRouteImport } from './routes/jobseeker'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobseekerIndexRouteImport } from './routes/jobseeker.index'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as JobseekerProfileRouteImport } from './routes/jobseeker.profile'
import { Route as JobseekerJobsRouteImport } from './routes/jobseeker.jobs'
import { Route as JobseekerAssistantRouteImport } from './routes/jobseeker.assistant'
import { Route as JobseekerApplicationsRouteImport } from './routes/jobseeker.applications'
import { Route as EmployerVacanciesRouteImport } from './routes/employer.vacancies'
import { Route as EmployerCandidatesRouteImport } from './routes/employer.candidates'
import { Route as EmployerAssistantRouteImport } from './routes/employer.assistant'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerRoute = JobseekerRouteImport.update({
  id: '/jobseeker',
  path: '/jobseeker',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerIndexRoute = JobseekerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobseekerRoute,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployerRoute,
} as any)
const JobseekerProfileRoute = JobseekerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => JobseekerRoute,
} as any)
const JobseekerJobsRoute = JobseekerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => JobseekerRoute,
} as any)
const JobseekerAssistantRoute = JobseekerAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => JobseekerRoute,
} as any)
const JobseekerApplicationsRoute = JobseekerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => JobseekerRoute,
} as any)
const EmployerVacanciesRoute = EmployerVacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerCandidatesRoute = EmployerCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerAssistantRoute = EmployerAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => EmployerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employer': typeof EmployerRouteWithChildren
  '/jobseeker': typeof JobseekerRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/employer/assistant': typeof EmployerAssistantRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/vacancies': typeof EmployerVacanciesRoute
  '/jobseeker/applications': typeof JobseekerApplicationsRoute
  '/jobseeker/assistant': typeof JobseekerAssistantRoute
  '/jobseeker/jobs': typeof JobseekerJobsRoute
  '/jobseeker/profile': typeof JobseekerProfileRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobseeker/': typeof JobseekerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/employer/assistant': typeof EmployerAssistantRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/vacancies': typeof EmployerVacanciesRoute
  '/jobseeker/applications': typeof JobseekerApplicationsRoute
  '/jobseeker/assistant': typeof JobseekerAssistantRoute
  '/jobseeker/jobs': typeof JobseekerJobsRoute
  '/jobseeker/profile': typeof JobseekerProfileRoute
  '/employer': typeof EmployerIndexRoute
  '/jobseeker': typeof JobseekerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employer': typeof EmployerRouteWithChildren
  '/jobseeker': typeof JobseekerRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/employer/assistant': typeof EmployerAssistantRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/vacancies': typeof EmployerVacanciesRoute
  '/jobseeker/applications': typeof JobseekerApplicationsRoute
  '/jobseeker/assistant': typeof JobseekerAssistantRoute
  '/jobseeker/jobs': typeof JobseekerJobsRoute
  '/jobseeker/profile': typeof JobseekerProfileRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobseeker/': typeof JobseekerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employer'
    | '/jobseeker'
    | '/login'
    | '/register'
    | '/employer/assistant'
    | '/employer/candidates'
    | '/employer/vacancies'
    | '/jobseeker/applications'
    | '/jobseeker/assistant'
    | '/jobseeker/jobs'
    | '/jobseeker/profile'
    | '/employer/'
    | '/jobseeker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/employer/assistant'
    | '/employer/candidates'
    | '/employer/vacancies'
    | '/jobseeker/applications'
    | '/jobseeker/assistant'
    | '/jobseeker/jobs'
    | '/jobseeker/profile'
    | '/employer'
    | '/jobseeker'
  id:
    | '__root__'
    | '/'
    | '/employer'
    | '/jobseeker'
    | '/login'
    | '/register'
    | '/employer/assistant'
    | '/employer/candidates'
    | '/employer/vacancies'
    | '/jobseeker/applications'
    | '/jobseeker/assistant'
    | '/jobseeker/jobs'
    | '/jobseeker/profile'
    | '/employer/'
    | '/jobseeker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployerRoute: typeof EmployerRouteWithChildren
  JobseekerRoute: typeof JobseekerRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker': {
      id: '/jobseeker'
      path: '/jobseeker'
      fullPath: '/jobseeker'
      preLoaderRoute: typeof JobseekerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker/': {
      id: '/jobseeker/'
      path: '/'
      fullPath: '/jobseeker/'
      preLoaderRoute: typeof JobseekerIndexRouteImport
      parentRoute: typeof JobseekerRoute
    }
    '/employer/': {
      id: '/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/jobseeker/profile': {
      id: '/jobseeker/profile'
      path: '/profile'
      fullPath: '/jobseeker/profile'
      preLoaderRoute: typeof JobseekerProfileRouteImport
      parentRoute: typeof JobseekerRoute
    }
    '/jobseeker/jobs': {
      id: '/jobseeker/jobs'
      path: '/jobs'
      fullPath: '/jobseeker/jobs'
      preLoaderRoute: typeof JobseekerJobsRouteImport
      parentRoute: typeof JobseekerRoute
    }
    '/jobseeker/assistant': {
      id: '/jobseeker/assistant'
      path: '/assistant'
      fullPath: '/jobseeker/assistant'
      preLoaderRoute: typeof JobseekerAssistantRouteImport
      parentRoute: typeof JobseekerRoute
    }
    '/jobseeker/applications': {
      id: '/jobseeker/applications'
      path: '/applications'
      fullPath: '/jobseeker/applications'
      preLoaderRoute: typeof JobseekerApplicationsRouteImport
      parentRoute: typeof JobseekerRoute
    }
    '/employer/vacancies': {
      id: '/employer/vacancies'
      path: '/vacancies'
      fullPath: '/employer/vacancies'
      preLoaderRoute: typeof EmployerVacanciesRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/candidates': {
      id: '/employer/candidates'
      path: '/candidates'
      fullPath: '/employer/candidates'
      preLoaderRoute: typeof EmployerCandidatesRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/assistant': {
      id: '/employer/assistant'
      path: '/assistant'
      fullPath: '/employer/assistant'
      preLoaderRoute: typeof EmployerAssistantRouteImport
      parentRoute: typeof EmployerRoute
    }
  }
}

interface EmployerRouteChildren {
  EmployerAssistantRoute: typeof EmployerAssistantRoute
  EmployerCandidatesRoute: typeof EmployerCandidatesRoute
  EmployerVacanciesRoute: typeof EmployerVacanciesRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
}

const EmployerRouteChildren: EmployerRouteChildren = {
  EmployerAssistantRoute: EmployerAssistantRoute,
  EmployerCandidatesRoute: EmployerCandidatesRoute,
  EmployerVacanciesRoute: EmployerVacanciesRoute,
  EmployerIndexRoute: EmployerIndexRoute,
}

const EmployerRouteWithChildren = EmployerRoute._addFileChildren(
  EmployerRouteChildren,
)

interface JobseekerRouteChildren {
  JobseekerApplicationsRoute: typeof JobseekerApplicationsRoute
  JobseekerAssistantRoute: typeof JobseekerAssistantRoute
  JobseekerJobsRoute: typeof JobseekerJobsRoute
  JobseekerProfileRoute: typeof JobseekerProfileRoute
  JobseekerIndexRoute: typeof JobseekerIndexRoute
}

const JobseekerRouteChildren: JobseekerRouteChildren = {
  JobseekerApplicationsRoute: JobseekerApplicationsRoute,
  JobseekerAssistantRoute: JobseekerAssistantRoute,
  JobseekerJobsRoute: JobseekerJobsRoute,
  JobseekerProfileRoute: JobseekerProfileRoute,
  JobseekerIndexRoute: JobseekerIndexRoute,
}

const JobseekerRouteWithChildren = JobseekerRoute._addFileChildren(
  JobseekerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployerRoute: EmployerRouteWithChildren,
  JobseekerRoute: JobseekerRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
