/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobseekerRouteImport } from './routes/jobseeker'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as CaseofficerRouteImport } from './routes/caseofficer'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobseekerIndexRouteImport } from './routes/jobseeker.index'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as CaseofficerIndexRouteImport } from './routes/caseofficer.index'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as JobseekerProfileRouteImport } from './routes/jobseeker.profile'
import { Route as JobseekerJobsRouteImport } from './routes/jobseeker.jobs'
import { Route as JobseekerCeeveeRouteImport } from './routes/jobseeker.ceevee'
import { Route as JobseekerAssistantRouteImport } from './routes/jobseeker.assistant'
import { Route as JobseekerApplicationsRouteImport } from './routes/jobseeker.applications'
import { Route as EmployerVacanciesRouteImport } from './routes/employer.vacancies'
import { Route as EmployerJdAnalyzerRouteImport } from './routes/employer.jd-analyzer'
import { Route as EmployerInterviewRouteImport } from './routes/employer.interview'
import { Route as EmployerFitMatchRouteImport } from './routes/employer.fit-match'
import { Route as EmployerEvaluationRouteImport } from './routes/employer.evaluation'
import { Route as EmployerCandidatesRouteImport } from './routes/employer.candidates'
import { Route as EmployerAssistantRouteImport } from './routes/employer.assistant'
import { Route as CaseofficerReportHubRouteImport } from './routes/caseofficer.report-hub'
import { Route as CaseofficerKnowledgeBaseRouteImport } from './routes/caseofficer.knowledge-base'
import { Route as AiTrainingRouteImport } from './routes/ai.training'
import { Route as AiJobMatchRouteImport } from './routes/ai.job-match'
import { Route as AiInterviewRouteImport } from './routes/ai.interview'
import { Route as AiCvRouteImport } from './routes/ai.cv'
import { Route as AiCareerRouteImport } from './routes/ai.career'
import { Route as JobseekerCeeveeStatusRouteImport } from './routes/jobseeker.ceevee.status'
import { Route as JobseekerCeeveeReviewRouteImport } from './routes/jobseeker.ceevee.review'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerRoute = JobseekerRouteImport.update({
  id: '/jobseeker',
  path: '/jobseeker',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseofficerRoute = CaseofficerRouteImport.update({
  id: '/caseofficer',
  path: '/caseofficer',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerIndexRoute = JobseekerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobseekerRoute,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployerRoute,
} as any)
const CaseofficerIndexRoute = CaseofficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseofficerRoute,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiRoute,
} as any)
const JobseekerProfileRoute = JobseekerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => JobseekerRoute,
} as any)
const JobseekerJobsRoute = JobseekerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => JobseekerRoute,
} as any)
const JobseekerCeeveeRoute = JobseekerCeeveeRouteImport.update({
  id: '/ceevee',
  path: '/ceevee',
  getParentRoute: () => JobseekerRoute,
} as any)
const JobseekerAssistantRoute = JobseekerAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => JobseekerRoute,
} as any)
const JobseekerApplicationsRoute = JobseekerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => JobseekerRoute,
} as any)
const EmployerVacanciesRoute = EmployerVacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerJdAnalyzerRoute = EmployerJdAnalyzerRouteImport.update({
  id: '/jd-analyzer',
  path: '/jd-analyzer',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerInterviewRoute = EmployerInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerFitMatchRoute = EmployerFitMatchRouteImport.update({
  id: '/fit-match',
  path: '/fit-match',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerEvaluationRoute = EmployerEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerCandidatesRoute = EmployerCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerAssistantRoute = EmployerAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => EmployerRoute,
} as any)
const CaseofficerReportHubRoute = CaseofficerReportHubRouteImport.update({
  id: '/report-hub',
  path: '/report-hub',
  getParentRoute: () => CaseofficerRoute,
} as any)
const CaseofficerKnowledgeBaseRoute =
  CaseofficerKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => CaseofficerRoute,
  } as any)
const AiTrainingRoute = AiTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AiRoute,
} as any)
const AiJobMatchRoute = AiJobMatchRouteImport.update({
  id: '/job-match',
  path: '/job-match',
  getParentRoute: () => AiRoute,
} as any)
const AiInterviewRoute = AiInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AiRoute,
} as any)
const AiCvRoute = AiCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AiRoute,
} as any)
const AiCareerRoute = AiCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AiRoute,
} as any)
const JobseekerCeeveeStatusRoute = JobseekerCeeveeStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => JobseekerCeeveeRoute,
} as any)
const JobseekerCeeveeReviewRoute = JobseekerCeeveeReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => JobseekerCeeveeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/caseofficer': typeof CaseofficerRouteWithChildren
  '/employer': typeof EmployerRouteWithChildren
  '/jobseeker': typeof JobseekerRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai/career': typeof AiCareerRoute
  '/ai/cv': typeof AiCvRoute
  '/ai/interview': typeof AiInterviewRoute
  '/ai/job-match': typeof AiJobMatchRoute
  '/ai/training': typeof AiTrainingRoute
  '/caseofficer/knowledge-base': typeof CaseofficerKnowledgeBaseRoute
  '/caseofficer/report-hub': typeof CaseofficerReportHubRoute
  '/employer/assistant': typeof EmployerAssistantRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/evaluation': typeof EmployerEvaluationRoute
  '/employer/fit-match': typeof EmployerFitMatchRoute
  '/employer/interview': typeof EmployerInterviewRoute
  '/employer/jd-analyzer': typeof EmployerJdAnalyzerRoute
  '/employer/vacancies': typeof EmployerVacanciesRoute
  '/jobseeker/applications': typeof JobseekerApplicationsRoute
  '/jobseeker/assistant': typeof JobseekerAssistantRoute
  '/jobseeker/ceevee': typeof JobseekerCeeveeRouteWithChildren
  '/jobseeker/jobs': typeof JobseekerJobsRoute
  '/jobseeker/profile': typeof JobseekerProfileRoute
  '/ai/': typeof AiIndexRoute
  '/caseofficer/': typeof CaseofficerIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobseeker/': typeof JobseekerIndexRoute
  '/jobseeker/ceevee/review': typeof JobseekerCeeveeReviewRoute
  '/jobseeker/ceevee/status': typeof JobseekerCeeveeStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai/career': typeof AiCareerRoute
  '/ai/cv': typeof AiCvRoute
  '/ai/interview': typeof AiInterviewRoute
  '/ai/job-match': typeof AiJobMatchRoute
  '/ai/training': typeof AiTrainingRoute
  '/caseofficer/knowledge-base': typeof CaseofficerKnowledgeBaseRoute
  '/caseofficer/report-hub': typeof CaseofficerReportHubRoute
  '/employer/assistant': typeof EmployerAssistantRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/evaluation': typeof EmployerEvaluationRoute
  '/employer/fit-match': typeof EmployerFitMatchRoute
  '/employer/interview': typeof EmployerInterviewRoute
  '/employer/jd-analyzer': typeof EmployerJdAnalyzerRoute
  '/employer/vacancies': typeof EmployerVacanciesRoute
  '/jobseeker/applications': typeof JobseekerApplicationsRoute
  '/jobseeker/assistant': typeof JobseekerAssistantRoute
  '/jobseeker/ceevee': typeof JobseekerCeeveeRouteWithChildren
  '/jobseeker/jobs': typeof JobseekerJobsRoute
  '/jobseeker/profile': typeof JobseekerProfileRoute
  '/ai': typeof AiIndexRoute
  '/caseofficer': typeof CaseofficerIndexRoute
  '/employer': typeof EmployerIndexRoute
  '/jobseeker': typeof JobseekerIndexRoute
  '/jobseeker/ceevee/review': typeof JobseekerCeeveeReviewRoute
  '/jobseeker/ceevee/status': typeof JobseekerCeeveeStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/caseofficer': typeof CaseofficerRouteWithChildren
  '/employer': typeof EmployerRouteWithChildren
  '/jobseeker': typeof JobseekerRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai/career': typeof AiCareerRoute
  '/ai/cv': typeof AiCvRoute
  '/ai/interview': typeof AiInterviewRoute
  '/ai/job-match': typeof AiJobMatchRoute
  '/ai/training': typeof AiTrainingRoute
  '/caseofficer/knowledge-base': typeof CaseofficerKnowledgeBaseRoute
  '/caseofficer/report-hub': typeof CaseofficerReportHubRoute
  '/employer/assistant': typeof EmployerAssistantRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/evaluation': typeof EmployerEvaluationRoute
  '/employer/fit-match': typeof EmployerFitMatchRoute
  '/employer/interview': typeof EmployerInterviewRoute
  '/employer/jd-analyzer': typeof EmployerJdAnalyzerRoute
  '/employer/vacancies': typeof EmployerVacanciesRoute
  '/jobseeker/applications': typeof JobseekerApplicationsRoute
  '/jobseeker/assistant': typeof JobseekerAssistantRoute
  '/jobseeker/ceevee': typeof JobseekerCeeveeRouteWithChildren
  '/jobseeker/jobs': typeof JobseekerJobsRoute
  '/jobseeker/profile': typeof JobseekerProfileRoute
  '/ai/': typeof AiIndexRoute
  '/caseofficer/': typeof CaseofficerIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobseeker/': typeof JobseekerIndexRoute
  '/jobseeker/ceevee/review': typeof JobseekerCeeveeReviewRoute
  '/jobseeker/ceevee/status': typeof JobseekerCeeveeStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/caseofficer'
    | '/employer'
    | '/jobseeker'
    | '/login'
    | '/register'
    | '/ai/career'
    | '/ai/cv'
    | '/ai/interview'
    | '/ai/job-match'
    | '/ai/training'
    | '/caseofficer/knowledge-base'
    | '/caseofficer/report-hub'
    | '/employer/assistant'
    | '/employer/candidates'
    | '/employer/evaluation'
    | '/employer/fit-match'
    | '/employer/interview'
    | '/employer/jd-analyzer'
    | '/employer/vacancies'
    | '/jobseeker/applications'
    | '/jobseeker/assistant'
    | '/jobseeker/ceevee'
    | '/jobseeker/jobs'
    | '/jobseeker/profile'
    | '/ai/'
    | '/caseofficer/'
    | '/employer/'
    | '/jobseeker/'
    | '/jobseeker/ceevee/review'
    | '/jobseeker/ceevee/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/ai/career'
    | '/ai/cv'
    | '/ai/interview'
    | '/ai/job-match'
    | '/ai/training'
    | '/caseofficer/knowledge-base'
    | '/caseofficer/report-hub'
    | '/employer/assistant'
    | '/employer/candidates'
    | '/employer/evaluation'
    | '/employer/fit-match'
    | '/employer/interview'
    | '/employer/jd-analyzer'
    | '/employer/vacancies'
    | '/jobseeker/applications'
    | '/jobseeker/assistant'
    | '/jobseeker/ceevee'
    | '/jobseeker/jobs'
    | '/jobseeker/profile'
    | '/ai'
    | '/caseofficer'
    | '/employer'
    | '/jobseeker'
    | '/jobseeker/ceevee/review'
    | '/jobseeker/ceevee/status'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/caseofficer'
    | '/employer'
    | '/jobseeker'
    | '/login'
    | '/register'
    | '/ai/career'
    | '/ai/cv'
    | '/ai/interview'
    | '/ai/job-match'
    | '/ai/training'
    | '/caseofficer/knowledge-base'
    | '/caseofficer/report-hub'
    | '/employer/assistant'
    | '/employer/candidates'
    | '/employer/evaluation'
    | '/employer/fit-match'
    | '/employer/interview'
    | '/employer/jd-analyzer'
    | '/employer/vacancies'
    | '/jobseeker/applications'
    | '/jobseeker/assistant'
    | '/jobseeker/ceevee'
    | '/jobseeker/jobs'
    | '/jobseeker/profile'
    | '/ai/'
    | '/caseofficer/'
    | '/employer/'
    | '/jobseeker/'
    | '/jobseeker/ceevee/review'
    | '/jobseeker/ceevee/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRouteWithChildren
  CaseofficerRoute: typeof CaseofficerRouteWithChildren
  EmployerRoute: typeof EmployerRouteWithChildren
  JobseekerRoute: typeof JobseekerRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker': {
      id: '/jobseeker'
      path: '/jobseeker'
      fullPath: '/jobseeker'
      preLoaderRoute: typeof JobseekerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caseofficer': {
      id: '/caseofficer'
      path: '/caseofficer'
      fullPath: '/caseofficer'
      preLoaderRoute: typeof CaseofficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker/': {
      id: '/jobseeker/'
      path: '/'
      fullPath: '/jobseeker/'
      preLoaderRoute: typeof JobseekerIndexRouteImport
      parentRoute: typeof JobseekerRoute
    }
    '/employer/': {
      id: '/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/caseofficer/': {
      id: '/caseofficer/'
      path: '/'
      fullPath: '/caseofficer/'
      preLoaderRoute: typeof CaseofficerIndexRouteImport
      parentRoute: typeof CaseofficerRoute
    }
    '/ai/': {
      id: '/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof AiRoute
    }
    '/jobseeker/profile': {
      id: '/jobseeker/profile'
      path: '/profile'
      fullPath: '/jobseeker/profile'
      preLoaderRoute: typeof JobseekerProfileRouteImport
      parentRoute: typeof JobseekerRoute
    }
    '/jobseeker/jobs': {
      id: '/jobseeker/jobs'
      path: '/jobs'
      fullPath: '/jobseeker/jobs'
      preLoaderRoute: typeof JobseekerJobsRouteImport
      parentRoute: typeof JobseekerRoute
    }
    '/jobseeker/ceevee': {
      id: '/jobseeker/ceevee'
      path: '/ceevee'
      fullPath: '/jobseeker/ceevee'
      preLoaderRoute: typeof JobseekerCeeveeRouteImport
      parentRoute: typeof JobseekerRoute
    }
    '/jobseeker/assistant': {
      id: '/jobseeker/assistant'
      path: '/assistant'
      fullPath: '/jobseeker/assistant'
      preLoaderRoute: typeof JobseekerAssistantRouteImport
      parentRoute: typeof JobseekerRoute
    }
    '/jobseeker/applications': {
      id: '/jobseeker/applications'
      path: '/applications'
      fullPath: '/jobseeker/applications'
      preLoaderRoute: typeof JobseekerApplicationsRouteImport
      parentRoute: typeof JobseekerRoute
    }
    '/employer/vacancies': {
      id: '/employer/vacancies'
      path: '/vacancies'
      fullPath: '/employer/vacancies'
      preLoaderRoute: typeof EmployerVacanciesRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/jd-analyzer': {
      id: '/employer/jd-analyzer'
      path: '/jd-analyzer'
      fullPath: '/employer/jd-analyzer'
      preLoaderRoute: typeof EmployerJdAnalyzerRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/interview': {
      id: '/employer/interview'
      path: '/interview'
      fullPath: '/employer/interview'
      preLoaderRoute: typeof EmployerInterviewRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/fit-match': {
      id: '/employer/fit-match'
      path: '/fit-match'
      fullPath: '/employer/fit-match'
      preLoaderRoute: typeof EmployerFitMatchRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/evaluation': {
      id: '/employer/evaluation'
      path: '/evaluation'
      fullPath: '/employer/evaluation'
      preLoaderRoute: typeof EmployerEvaluationRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/candidates': {
      id: '/employer/candidates'
      path: '/candidates'
      fullPath: '/employer/candidates'
      preLoaderRoute: typeof EmployerCandidatesRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/assistant': {
      id: '/employer/assistant'
      path: '/assistant'
      fullPath: '/employer/assistant'
      preLoaderRoute: typeof EmployerAssistantRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/caseofficer/report-hub': {
      id: '/caseofficer/report-hub'
      path: '/report-hub'
      fullPath: '/caseofficer/report-hub'
      preLoaderRoute: typeof CaseofficerReportHubRouteImport
      parentRoute: typeof CaseofficerRoute
    }
    '/caseofficer/knowledge-base': {
      id: '/caseofficer/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/caseofficer/knowledge-base'
      preLoaderRoute: typeof CaseofficerKnowledgeBaseRouteImport
      parentRoute: typeof CaseofficerRoute
    }
    '/ai/training': {
      id: '/ai/training'
      path: '/training'
      fullPath: '/ai/training'
      preLoaderRoute: typeof AiTrainingRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/job-match': {
      id: '/ai/job-match'
      path: '/job-match'
      fullPath: '/ai/job-match'
      preLoaderRoute: typeof AiJobMatchRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/interview': {
      id: '/ai/interview'
      path: '/interview'
      fullPath: '/ai/interview'
      preLoaderRoute: typeof AiInterviewRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/cv': {
      id: '/ai/cv'
      path: '/cv'
      fullPath: '/ai/cv'
      preLoaderRoute: typeof AiCvRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/career': {
      id: '/ai/career'
      path: '/career'
      fullPath: '/ai/career'
      preLoaderRoute: typeof AiCareerRouteImport
      parentRoute: typeof AiRoute
    }
    '/jobseeker/ceevee/status': {
      id: '/jobseeker/ceevee/status'
      path: '/status'
      fullPath: '/jobseeker/ceevee/status'
      preLoaderRoute: typeof JobseekerCeeveeStatusRouteImport
      parentRoute: typeof JobseekerCeeveeRoute
    }
    '/jobseeker/ceevee/review': {
      id: '/jobseeker/ceevee/review'
      path: '/review'
      fullPath: '/jobseeker/ceevee/review'
      preLoaderRoute: typeof JobseekerCeeveeReviewRouteImport
      parentRoute: typeof JobseekerCeeveeRoute
    }
  }
}

interface AiRouteChildren {
  AiCareerRoute: typeof AiCareerRoute
  AiCvRoute: typeof AiCvRoute
  AiInterviewRoute: typeof AiInterviewRoute
  AiJobMatchRoute: typeof AiJobMatchRoute
  AiTrainingRoute: typeof AiTrainingRoute
  AiIndexRoute: typeof AiIndexRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiCareerRoute: AiCareerRoute,
  AiCvRoute: AiCvRoute,
  AiInterviewRoute: AiInterviewRoute,
  AiJobMatchRoute: AiJobMatchRoute,
  AiTrainingRoute: AiTrainingRoute,
  AiIndexRoute: AiIndexRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface CaseofficerRouteChildren {
  CaseofficerKnowledgeBaseRoute: typeof CaseofficerKnowledgeBaseRoute
  CaseofficerReportHubRoute: typeof CaseofficerReportHubRoute
  CaseofficerIndexRoute: typeof CaseofficerIndexRoute
}

const CaseofficerRouteChildren: CaseofficerRouteChildren = {
  CaseofficerKnowledgeBaseRoute: CaseofficerKnowledgeBaseRoute,
  CaseofficerReportHubRoute: CaseofficerReportHubRoute,
  CaseofficerIndexRoute: CaseofficerIndexRoute,
}

const CaseofficerRouteWithChildren = CaseofficerRoute._addFileChildren(
  CaseofficerRouteChildren,
)

interface EmployerRouteChildren {
  EmployerAssistantRoute: typeof EmployerAssistantRoute
  EmployerCandidatesRoute: typeof EmployerCandidatesRoute
  EmployerEvaluationRoute: typeof EmployerEvaluationRoute
  EmployerFitMatchRoute: typeof EmployerFitMatchRoute
  EmployerInterviewRoute: typeof EmployerInterviewRoute
  EmployerJdAnalyzerRoute: typeof EmployerJdAnalyzerRoute
  EmployerVacanciesRoute: typeof EmployerVacanciesRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
}

const EmployerRouteChildren: EmployerRouteChildren = {
  EmployerAssistantRoute: EmployerAssistantRoute,
  EmployerCandidatesRoute: EmployerCandidatesRoute,
  EmployerEvaluationRoute: EmployerEvaluationRoute,
  EmployerFitMatchRoute: EmployerFitMatchRoute,
  EmployerInterviewRoute: EmployerInterviewRoute,
  EmployerJdAnalyzerRoute: EmployerJdAnalyzerRoute,
  EmployerVacanciesRoute: EmployerVacanciesRoute,
  EmployerIndexRoute: EmployerIndexRoute,
}

const EmployerRouteWithChildren = EmployerRoute._addFileChildren(
  EmployerRouteChildren,
)

interface JobseekerCeeveeRouteChildren {
  JobseekerCeeveeReviewRoute: typeof JobseekerCeeveeReviewRoute
  JobseekerCeeveeStatusRoute: typeof JobseekerCeeveeStatusRoute
}

const JobseekerCeeveeRouteChildren: JobseekerCeeveeRouteChildren = {
  JobseekerCeeveeReviewRoute: JobseekerCeeveeReviewRoute,
  JobseekerCeeveeStatusRoute: JobseekerCeeveeStatusRoute,
}

const JobseekerCeeveeRouteWithChildren = JobseekerCeeveeRoute._addFileChildren(
  JobseekerCeeveeRouteChildren,
)

interface JobseekerRouteChildren {
  JobseekerApplicationsRoute: typeof JobseekerApplicationsRoute
  JobseekerAssistantRoute: typeof JobseekerAssistantRoute
  JobseekerCeeveeRoute: typeof JobseekerCeeveeRouteWithChildren
  JobseekerJobsRoute: typeof JobseekerJobsRoute
  JobseekerProfileRoute: typeof JobseekerProfileRoute
  JobseekerIndexRoute: typeof JobseekerIndexRoute
}

const JobseekerRouteChildren: JobseekerRouteChildren = {
  JobseekerApplicationsRoute: JobseekerApplicationsRoute,
  JobseekerAssistantRoute: JobseekerAssistantRoute,
  JobseekerCeeveeRoute: JobseekerCeeveeRouteWithChildren,
  JobseekerJobsRoute: JobseekerJobsRoute,
  JobseekerProfileRoute: JobseekerProfileRoute,
  JobseekerIndexRoute: JobseekerIndexRoute,
}

const JobseekerRouteWithChildren = JobseekerRoute._addFileChildren(
  JobseekerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRouteWithChildren,
  CaseofficerRoute: CaseofficerRouteWithChildren,
  EmployerRoute: EmployerRouteWithChildren,
  JobseekerRoute: JobseekerRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
